apiVersion: apps/v1
kind: Deployment
metadata:
  name: playtodied-bot
  labels:
    app.kubernetes.io/name: playtodied-bot
    app.kubernetes.io/instance: playtodied-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: playtodied-bot
      app.kubernetes.io/instance: playtodied-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: playtodied-bot
        app.kubernetes.io/instance: playtodied-bot
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: node.kubernetes.io/instance-type
      #           operator: In
      #           values:
      #           - vhp-2c-2gb-amd  
      imagePullSecrets:
        - name: dockersecret      
      serviceAccountName: playtodied-bot
      securityContext:
        {}
      containers:
        - name: app
          securityContext:
            {}
          image: "whthduck/playtodied-bot:latest"
          imagePullPolicy: Always
          env:         
          - name: APP_NAME
            value: "playtodied-bot"    
          - name: APP_SECRET
            value: "89116e9e-3f42-4b54-bd07-060b269fde2f"
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "8080"
          - name: PLAYTODIED_DISCORD_TOKEN
            valueFrom: 
              secretKeyRef:
                name: whthduck-creds
                key: playtodied-discord-token
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP  
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: http
            periodSeconds: 10        
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi