# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: playtodied-bot
#   labels:
#     app.kubernetes.io/name: playtodied-bot
#     app.kubernetes.io/instance: playtodied-bot
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-prod
#     external-dns.alpha.kubernetes.io/ttl: 5m
#     kubernetes.io/ingress.class: nginx
# spec:
#   tls:
#     - hosts:
#         - "productive.workmind.app"
#       secretName: productive-workmind-app-tls
#   rules:
#     - host: "productive.workmind.app"
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: playtodied-bot
#                 port:
#                   number: 8080
