apiVersion: v1
kind: Service
metadata:
  name: playtodied-bot
  labels:
    app.kubernetes.io/name: playtodied-bot
    app.kubernetes.io/instance: playtodied-bot
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: playtodied-bot
    app.kubernetes.io/instance: playtodied-bot